apiVersion: v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    app: demo-voting-app
# Pod has containers , if Service i would have ports
# goto docker images and find example voting app image
# https://github.com/bfirsh/example-voting-app
# image exposes at port 6379  in memory database port
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-app-pod
      app:  demo-voting-app
  # Pod template is copied from result-pod.yml
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: demo-voting-app
    # Pod has containers , if Service i would have ports
    # goto docker images and find example voting app image
    # https://github.com/bfirsh/example-voting-app
    # image exposes at port 80
    spec:
      containers:
        - name: result-app
          image: dockersamples/examplevotingapp_result

          ports:
            - containerPort: 80