apiVersion: v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    app: demo-voting-app
# Pod has containers , if Service i would have ports
# goto docker images and find example voting app image
# https://github.com/bfirsh/example-voting-app
# image exposes at port 6379  in memory database port
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app-pod
      app:  demo-voting-app
  # Pod template is copied from worker-pod.yml
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: demo-voting-app
    # Pod has containers , if Service i would have ports
    # goto docker images and find example voting app image
    # https://github.com/bfirsh/example-voting-app
    # worker image does not exposes at port 80 (internal application)
    spec:
      containers:
        - name: worker-app
          image: dockersamples/examplevotingapp_worker